<?php

namespace Xhprof\GuiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilingRepository extends EntityRepository
{
}
